#!/bin/bash

CMD=$1
po="po/"$CMD".1.zh_CN.po"
master="raw/man1/"$CMD".1"
target="/tmp/"$CMD".1"

if [ "x$1" = "x" ]; then
    echo "Invalid argument."
    exit 1
fi
which po4a-translate > /dev/null 2>&1
if [ ! "x$?" = "x0" ]; then
    echo "Sorry, you need to install po4a first."
    exit 1
fi
echo $master
if [ ! -e $master ]; then
    echo "$CMD has not been translated or does exist at all."
    exit 1
fi

sed -e "s/fuzzy//g" $po > /tmp/tmp.po
po4a-translate -f man -m $master -p /tmp/tmp.po -l /tmp/tmp.1
echo ". mso zh.tmac" > /tmp/ChineseSupport
if [ ! -e /tmp/tmp.1 ]; then
    echo "Ooops, cannot generate the translated $target"
    exit
fi
cat /tmp/ChineseSupport /tmp/tmp.1 > $target
man $target
